Watching for file changes with StatReloader
[22/Apr/2020 19:12:32] "GET /e/azizm17 HTTP/1.1" 301 0
[22/Apr/2020 19:12:32] "GET /e/azizm17/ HTTP/1.1" 200 4623
[22/Apr/2020 19:12:40] "POST /e/azizm17/ HTTP/1.1" 302 0
[22/Apr/2020 19:12:40] "GET /e/azizm17/social/messages/ HTTP/1.1" 200 7028
[22/Apr/2020 19:12:52] "GET /e/azizm17/logout/ HTTP/1.1" 302 0
[22/Apr/2020 19:12:52] "GET /e/azizm17/ HTTP/1.1" 200 4623
/home/azizm17/private/CS1XA3/Project03/login/urls.py changed, reloading.
Performing system checks...

System check identified no issues (0 silenced).
April 22, 2020 - 19:11:20
Django version 3.0.3, using settings 'Project03.settings'
Starting development server at http://localhost:10010/
Quit the server with CONTROL-C.
Watching for file changes with StatReloader
Exception in thread django-main-thread:
Traceback (most recent call last):
  File "/opt/anaconda3/envs/djangoenv/lib/python3.7/threading.py", line 926, in _bootstrap_inner
    self.run()
  File "/opt/anaconda3/envs/djangoenv/lib/python3.7/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/opt/anaconda3/envs/djangoenv/lib/python3.7/site-packages/django/utils/autoreload.py", line 53, in wrapper
    fn(*args, **kwargs)
  File "/opt/anaconda3/envs/djangoenv/lib/python3.7/site-packages/django/core/management/commands/runserver.py", line 117, in inner_run
    self.check(display_num_errors=True)
  File "/opt/anaconda3/envs/djangoenv/lib/python3.7/site-packages/django/core/management/base.py", line 395, in check
    include_deployment_checks=include_deployment_checks,
  File "/opt/anaconda3/envs/djangoenv/lib/python3.7/site-packages/django/core/management/base.py", line 382, in _run_checks
    return checks.run_checks(**kwargs)
  File "/opt/anaconda3/envs/djangoenv/lib/python3.7/site-packages/django/core/checks/registry.py", line 72, in run_checks
    new_errors = check(app_configs=app_configs)
  File "/opt/anaconda3/envs/djangoenv/lib/python3.7/site-packages/django/core/checks/urls.py", line 13, in check_url_config
    return check_resolver(resolver)
  File "/opt/anaconda3/envs/djangoenv/lib/python3.7/site-packages/django/core/checks/urls.py", line 23, in check_resolver
    return check_method()
  File "/opt/anaconda3/envs/djangoenv/lib/python3.7/site-packages/django/urls/resolvers.py", line 407, in check
    for pattern in self.url_patterns:
  File "/opt/anaconda3/envs/djangoenv/lib/python3.7/site-packages/django/utils/functional.py", line 48, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/opt/anaconda3/envs/djangoenv/lib/python3.7/site-packages/django/urls/resolvers.py", line 588, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/opt/anaconda3/envs/djangoenv/lib/python3.7/site-packages/django/utils/functional.py", line 48, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/opt/anaconda3/envs/djangoenv/lib/python3.7/site-packages/django/urls/resolvers.py", line 581, in urlconf_module
    return import_module(self.urlconf_name)
  File "/opt/anaconda3/envs/djangoenv/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/azizm17/private/CS1XA3/Project03/Project03/urls.py", line 19, in <module>
    path('e/azizm17/', include('login.urls')),
  File "/opt/anaconda3/envs/djangoenv/lib/python3.7/site-packages/django/urls/conf.py", line 34, in include
    urlconf_module = import_module(urlconf_module)
  File "/opt/anaconda3/envs/djangoenv/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/azizm17/private/CS1XA3/Project03/login/urls.py", line 24, in <module>
    path('create/', view.user_create_view, name="create_view"),
NameError: name 'view' is not defined

/home/azizm17/private/CS1XA3/Project03/login/views.py changed, reloading.
Performing system checks...

Watching for file changes with StatReloader
Watching for file changes with StatReloader
Watching for file changes with StatReloader
Performing system checks...

System check identified no issues (0 silenced).
April 22, 2020 - 20:05:23
Django version 3.0.3, using settings 'Project03.settings'
Starting development server at http://localhost:10010/
Quit the server with CONTROL-C.
Watching for file changes with StatReloader
[22/Apr/2020 20:05:51] "GET /e/azizm17/social/messages/ HTTP/1.1" 200 5941
Watching for file changes with StatReloader
[22/Apr/2020 20:10:54] "GET /e/azizm17/social/account/ HTTP/1.1" 200 6145
[22/Apr/2020 20:10:57] "POST /e/azizm17/social/user/ HTTP/1.1" 200 6768
[22/Apr/2020 20:11:03] "POST /e/azizm17/social/user/ HTTP/1.1" 302 0
[22/Apr/2020 20:11:03] "GET /e/azizm17/social/messages/ HTTP/1.1" 200 6051
[22/Apr/2020 20:11:10] "GET /e/azizm17/logout/ HTTP/1.1" 302 0
[22/Apr/2020 20:11:10] "GET /e/azizm17/ HTTP/1.1" 200 4623
[22/Apr/2020 20:11:12] "POST /e/azizm17/ HTTP/1.1" 302 0
[22/Apr/2020 20:11:12] "GET /e/azizm17/social/messages/ HTTP/1.1" 200 6051
[22/Apr/2020 20:11:15] "GET /e/azizm17/ HTTP/1.1" 200 4623
[22/Apr/2020 20:11:19] "POST /e/azizm17/ HTTP/1.1" 302 0
[22/Apr/2020 20:11:19] "GET /e/azizm17/social/messages/ HTTP/1.1" 200 5944
[22/Apr/2020 20:11:21] "GET /e/azizm17/social/account/ HTTP/1.1" 200 6148
[22/Apr/2020 20:11:22] "POST /e/azizm17/social/user/ HTTP/1.1" 200 6771
[22/Apr/2020 20:11:30] "POST /e/azizm17/social/user/ HTTP/1.1" 302 0
[22/Apr/2020 20:11:30] "GET /e/azizm17/social/messages/ HTTP/1.1" 200 6051
[22/Apr/2020 20:11:32] "GET /e/azizm17/social/people/ HTTP/1.1" 200 6439
[22/Apr/2020 20:11:34] "POST /e/azizm17/social/friendrequest/ HTTP/1.1" 200 0
[22/Apr/2020 20:11:34] "GET /e/azizm17/social/people/ HTTP/1.1" 200 6439
[22/Apr/2020 20:11:36] "GET /e/azizm17/logout/ HTTP/1.1" 302 0
[22/Apr/2020 20:11:36] "GET /e/azizm17/ HTTP/1.1" 200 4623
[22/Apr/2020 20:11:40] "POST /e/azizm17/ HTTP/1.1" 302 0
[22/Apr/2020 20:11:40] "GET /e/azizm17/social/messages/ HTTP/1.1" 200 6051
[22/Apr/2020 20:11:41] "GET /e/azizm17/social/people/ HTTP/1.1" 200 7531
[22/Apr/2020 20:12:03] "POST /e/azizm17/social/moreppl/ HTTP/1.1" 200 0
[22/Apr/2020 20:12:03] "GET /e/azizm17/social/people/ HTTP/1.1" 200 7531
[22/Apr/2020 20:12:05] "GET /e/azizm17/social/people/ HTTP/1.1" 200 7531
[22/Apr/2020 20:12:06] "GET /e/azizm17/social/messages/ HTTP/1.1" 200 6051
[22/Apr/2020 20:12:07] "GET /e/azizm17/logout/ HTTP/1.1" 302 0
[22/Apr/2020 20:12:07] "GET /e/azizm17/ HTTP/1.1" 200 4623
[22/Apr/2020 20:12:10] "POST /e/azizm17/ HTTP/1.1" 302 0
[22/Apr/2020 20:12:10] "GET /e/azizm17/social/messages/ HTTP/1.1" 200 6051
[22/Apr/2020 20:12:13] "GET /e/azizm17/social/people/ HTTP/1.1" 200 6439
Watching for file changes with StatReloader
[22/Apr/2020 20:58:45] "GET /e/azizm17/ HTTP/1.1" 200 4623
[22/Apr/2020 20:58:51] "GET /e/azizm17/create/ HTTP/1.1" 302 0
[22/Apr/2020 20:58:51] "GET /e/azizm17/signup/ HTTP/1.1" 200 3934
[22/Apr/2020 20:59:00] "GET /e/azizm17/signup/ HTTP/1.1" 200 3934
[22/Apr/2020 20:59:14] "GET /e/azizm17/signup HTTP/1.1" 301 0
[22/Apr/2020 20:59:14] "GET /e/azizm17/signup/ HTTP/1.1" 200 3934
[22/Apr/2020 21:25:42] "POST /e/azizm17/ HTTP/1.1" 302 0
[22/Apr/2020 21:25:42] "GET /e/azizm17/social/messages/ HTTP/1.1" 200 6051
[22/Apr/2020 21:25:45] "GET /e/azizm17/social/messages/ HTTP/1.1" 200 6051
[22/Apr/2020 21:25:47] "GET /e/azizm17/social/people/ HTTP/1.1" 200 6439
[22/Apr/2020 21:25:48] "GET /e/azizm17/social/account/ HTTP/1.1" 200 6255
Watching for file changes with StatReloader
[22/Apr/2020 22:27:15] "GET /e/azizm17/logout/ HTTP/1.1" 302 0
[22/Apr/2020 22:27:15] "GET /e/azizm17/ HTTP/1.1" 200 4623
[22/Apr/2020 22:27:23] "GET /e/azizm17/social/messages HTTP/1.1" 301 0
[22/Apr/2020 22:27:23] "GET /e/azizm17/social/messages/ HTTP/1.1" 302 0
[22/Apr/2020 22:27:23] "GET /e/azizm17/ HTTP/1.1" 200 4623
[22/Apr/2020 22:27:31] "GET /e/azizm17/social/account HTTP/1.1" 301 0
[22/Apr/2020 22:27:32] "GET /e/azizm17/social/account/ HTTP/1.1" 302 0
[22/Apr/2020 22:27:32] "GET /e/azizm17/ HTTP/1.1" 200 4623
[22/Apr/2020 22:27:43] "GET /e/azizm17/social/people HTTP/1.1" 301 0
[22/Apr/2020 22:27:43] "GET /e/azizm17/social/people/ HTTP/1.1" 302 0
[22/Apr/2020 22:27:43] "GET /e/azizm17/ HTTP/1.1" 200 4623
/home/azizm17/private/CS1XA3/Project03/social/views.py changed, reloading.
Performing system checks...

System check identified no issues (0 silenced).
April 22, 2020 - 22:27:12
Django version 3.0.3, using settings 'Project03.settings'
Starting development server at http://localhost:10010/
Quit the server with CONTROL-C.
Watching for file changes with StatReloader
/home/azizm17/private/CS1XA3/Project03/social/views.py changed, reloading.
Performing system checks...

System check identified no issues (0 silenced).
April 22, 2020 - 23:55:16
Django version 3.0.3, using settings 'Project03.settings'
Starting development server at http://localhost:10010/
Quit the server with CONTROL-C.
Watching for file changes with StatReloader
